parameters:
#    crud_test.example.class: Crud\TestBundle\Example

services:
#    crud_test.example:
#        class: %crud_test.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
